### PR TITLE
Implement an assembler & disassembler

### PR DESCRIPTION
**Pull request by ricky26**
Hi! This is a draft PR implementing a (dis)assembler for M68k.

It's not entirely complete but I am able to compile a trivial C file, use objdump to fetch assembly and then use `clang -cc1as` to re-assemble it.

I recognise this is probably not the greatest time to get a PR like this due to the current work to upstream the M68k backend but I'm happy to rework this as necessary.

There's some pretty inefficient code in the disassembler because I couldn't find a way to have the code beads generator produce some needed tables without knowing things it shouldn't know about the backend.

### CODE REVIEW

**Comment by mshockwave** [comment]
Great! glad to see this. As you probably have heard, this project will merge into upstream LLVM pretty soon and I will probably put this repo into read-only.
Nevertheless, I highly recommend you to continue this work and send patches to upstream when you think it's ready. Feel free to contact me if you're not sure how LLVM's contribution process works (setting up Phab review, for example)

**Comment by ricky26** [comment]
Makes sense, I did suspect the way to go would be to aim for upstream once your patches landed. I just wanted to at least open a draft here so that the work didn't get doubled up. :smile:

**Comment by ricky26** [comment]
I'm closing this so I don't cause undue noise here.

**Comment by glaubitz** [comment]
> Hi! This is a draft PR implementing a (dis)assembler for M68k.
> 
> It's not entirely complete but I am able to compile a trivial C file, use objdump to fetch assembly and then use `clang -cc1as` to re-assemble it.

Awesome, I just saw this. Thanks a lot for this work and I hope we can get your stuff upstreamed as soon as possible.

I'm very excited to see people from outside contribute - just as I had hoped for the project :smiley:

**Comment by glaubitz** [comment]
I have created a tracking bug for both the AsmParser and Disassembler now:

> https://bugs.llvm.org/show_bug.cgi?id=48976

Feel free to subscribe to the bug report.

**Comment by mshockwave** [comment]
@ricky26 just a FYI that this backend has been upstreamed!

**Pull request closed without merging**
